### ISSUE TITLE
Pace refactor

### ISSUE THREAD

**Issue by FlorianDeconinck** [NOAA-GFDL/pace#53]
See https://github.com/GEOS-ESM/pace/issues/41

**Comment by bensonr** [comment]
@FlorianDeconinck - [NDSL](https://github.com/NOAA-GFDL/NDSL), [PyFV3](https://github.com/NOAA-GFDL/PyFV3), and [PySHiELD](https://github.com/NOAA-GFDL/PySHiELD) have been created in the NOAA-GFDL organization.  One the current PRs are accepted and merged, I think we can proceed with the plan.

**Comment by FlorianDeconinck** [comment]
👍 

`Github` doesn't allow me to cross-post issues or move an issue from our GEOS-ESM project into the NOAA-GFDL, so we'll track progress on the https://github.com/GEOS-ESM/pace/issues/41 side of things, and I'll cross post a summary here

**Comment by bensonr** [comment]
I started to add this info in the NASA PR, but thought maybe you wouldn't want clutter info about the a different org in your PR.

**Comment by FlorianDeconinck** [comment]
I think it's good info on the issue, I don't segregate it's all Open Source. I would have rather put everything here but Github is not allowing me so we might have those kind of cross-posting issue often

**Comment by FlorianDeconinck** [comment]
`ndsl` is in. Much clean up needs to happen but the basics are done and moved in `Pace`

**Comment by FlorianDeconinck** [comment]
`pyFV3` and `pySHiELD` have been created and their `main` branch is now protected (discussion on git strategy to follow)

`Pace` has been refactored to bring together all the packages.

**Comment by FlorianDeconinck** [comment]
Remaining task:
- `docs` needs splitting
- `Makefile` workflow is broken in all repositories
- `docker` is broken in all repositories

Clean up on naming and random bits will be an ongoing effort.

**Comment by FlorianDeconinck** [comment]
New repositories:
[ndsl](https://github.com/NOAA-GFDL/NDSL)
[pyFV3](https://github.com/NOAA-GFDL/pyFV3)
[pySHiELD](https://github.com/NOAA-GFDL/pySHiELD)
