### ISSUE TITLE
pace git clone fails in a container 

### ISSUE THREAD

**Issue by mlee03** [NOAA-GFDL/pace#63]
Cloning pace via `git clone --recursive https://github.com/NOAA-GFDL/pace.git` fails in a container due to publickey errors.  

The .gitmodules file should be specified with  https uris instead of ssh urls.

**Comment by FlorianDeconinck** [comment]
Do a pass on `ndsl` as well with the asme fix

**Comment by mlee03** [comment]
@FlorianDeconinck, seems like ndsl doesn't need the fix, it uses the https urls

**Comment by FlorianDeconinck** [comment]
Done with #65
