### ISSUE TITLE
file tests/main/input/eta79.nc does not exist

### ISSUE THREAD

**Issue by cponder** [NOAA-GFDL/pace#97]
I'm following the instructions on the main page; I ran the command
```
mpirun -n 6 --oversubscribe python3 -m pace.run examples/configs/baroclinic_c12.yaml
```
which gave a lot of output, but hit this message
```
ValueError: file tests/main/input/eta79.nc does not exist
```
I don't see this in your GIT tree, is there an extra step that downloads or generates it?

**Comment by fmalatino** [comment]
Hi Carl,

Yes, sorry about that we are a bit behind on updating the docs at the
moment. If you run the script ‘generate_eta_files.py’ in the ‘examples’
directory you will be able to generate the files. To use the
‘baroclinic_c12.yaml’ configuration you will need to generate an ‘input’
directory within ‘tests/main’ and move the generated files into the new
directory. If you run these exact commands at the top level of your clone
you should get everything that you need:

‘mkdir tests/main/input’
‘python3 examples/generate_eta_files.py’
‘mv *eta*.nc tests/main/input’

Thanks for pointing out this lapse in the docs and don’t hesitate to reach
out if you have any other issues.

**Comment by bensonr** [comment]
@fmalatino - can you create an issue to update the high level docs?

**Comment by cponder** [comment]
Along the same lines, I don't get an ```output.zarr``` directory, but I do get an `output` directory with these contents:
```
constants_lat.nc
constants_lat_agrid.nc
constants_lon.nc
constants_lon_agrid.nc
state_0000_tile0.nc
state_0000_tile1.nc
state_0000_tile2.nc
state_0000_tile3.nc
state_0000_tile4.nc
state_0000_tile5.nc
state_0001_tile0.nc
state_0001_tile1.nc
state_0001_tile2.nc
state_0001_tile3.nc
state_0001_tile4.nc
state_0001_tile5.nc
state_0002_tile0.nc
state_0002_tile1.nc
state_0002_tile2.nc
state_0002_tile3.nc
state_0002_tile4.nc
state_0002_tile5.nc
state_0003_tile0.nc
state_0003_tile1.nc
state_0003_tile2.nc
state_0003_tile3.nc
state_0003_tile4.nc
state_0003_tile5.nc
```

**Comment by fmalatino** [comment]
It seems as though someone (probably me while testing) changed the output to netcdf. In the PR attached to this issue I have now corrected it such that the output files from the run will be in `output.zarr` and the plots can be generated by running:
```
python examples/plot_output.py
```
from the top level of the cloned repository. So you don't have to wait for the PR to be merged in, in `baroclinic_c12.yaml` change the `path` variable under the `diagnostics_config` section from `path: output` to `path: output.zarr` and make sure that `output_format: zarr`

```
...
diagnostics_config:
  path: output.zarr
  output_format: zarr
  names:
  ...
  ```

**Comment by cponder** [comment]
One more -- I'm using the latest BOOST, version 1.87.0, and didn't see any problems.
The instructions say to use 1.79.0, though, is there a reason for that?

**Comment by fmalatino** [comment]
No worries, keep finding issues! And there is no reason aside from that BOOST needs to be at that version as a minimum.
